# CMAKE generated file: DO NOT EDIT!
# Generated by "MinGW Makefiles" Generator, CMake Version 3.4

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = "C:\Program Files (x86)\CMake\bin\cmake.exe"

# The command to remove a file.
RM = "C:\Program Files (x86)\CMake\bin\cmake.exe" -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = D:\CloudStation\GitHub\TSiD

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = D:\CloudStation\GitHub\TSiD

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	"C:\Program Files (x86)\CMake\bin\cmake-gui.exe" -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	"C:\Program Files (x86)\CMake\bin\cmake.exe" -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start D:\CloudStation\GitHub\TSiD\CMakeFiles D:\CloudStation\GitHub\TSiD\CMakeFiles\progress.marks
	$(MAKE) -f CMakeFiles\Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start D:\CloudStation\GitHub\TSiD\CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles\Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named server0

# Build rule for target.
server0: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 server0
.PHONY : server0

# fast build rule for target.
server0/fast:
	$(MAKE) -f CMakeFiles\server0.dir\build.make CMakeFiles/server0.dir/build
.PHONY : server0/fast

src/common/fileExist.obj: src/common/fileExist.cpp.obj

.PHONY : src/common/fileExist.obj

# target to build an object file
src/common/fileExist.cpp.obj:
	$(MAKE) -f CMakeFiles\server0.dir\build.make CMakeFiles/server0.dir/src/common/fileExist.cpp.obj
.PHONY : src/common/fileExist.cpp.obj

src/common/fileExist.i: src/common/fileExist.cpp.i

.PHONY : src/common/fileExist.i

# target to preprocess a source file
src/common/fileExist.cpp.i:
	$(MAKE) -f CMakeFiles\server0.dir\build.make CMakeFiles/server0.dir/src/common/fileExist.cpp.i
.PHONY : src/common/fileExist.cpp.i

src/common/fileExist.s: src/common/fileExist.cpp.s

.PHONY : src/common/fileExist.s

# target to generate assembly for a file
src/common/fileExist.cpp.s:
	$(MAKE) -f CMakeFiles\server0.dir\build.make CMakeFiles/server0.dir/src/common/fileExist.cpp.s
.PHONY : src/common/fileExist.cpp.s

src/server0/download.obj: src/server0/download.cpp.obj

.PHONY : src/server0/download.obj

# target to build an object file
src/server0/download.cpp.obj:
	$(MAKE) -f CMakeFiles\server0.dir\build.make CMakeFiles/server0.dir/src/server0/download.cpp.obj
.PHONY : src/server0/download.cpp.obj

src/server0/download.i: src/server0/download.cpp.i

.PHONY : src/server0/download.i

# target to preprocess a source file
src/server0/download.cpp.i:
	$(MAKE) -f CMakeFiles\server0.dir\build.make CMakeFiles/server0.dir/src/server0/download.cpp.i
.PHONY : src/server0/download.cpp.i

src/server0/download.s: src/server0/download.cpp.s

.PHONY : src/server0/download.s

# target to generate assembly for a file
src/server0/download.cpp.s:
	$(MAKE) -f CMakeFiles\server0.dir\build.make CMakeFiles/server0.dir/src/server0/download.cpp.s
.PHONY : src/server0/download.cpp.s

src/server0/listFiles.obj: src/server0/listFiles.cpp.obj

.PHONY : src/server0/listFiles.obj

# target to build an object file
src/server0/listFiles.cpp.obj:
	$(MAKE) -f CMakeFiles\server0.dir\build.make CMakeFiles/server0.dir/src/server0/listFiles.cpp.obj
.PHONY : src/server0/listFiles.cpp.obj

src/server0/listFiles.i: src/server0/listFiles.cpp.i

.PHONY : src/server0/listFiles.i

# target to preprocess a source file
src/server0/listFiles.cpp.i:
	$(MAKE) -f CMakeFiles\server0.dir\build.make CMakeFiles/server0.dir/src/server0/listFiles.cpp.i
.PHONY : src/server0/listFiles.cpp.i

src/server0/listFiles.s: src/server0/listFiles.cpp.s

.PHONY : src/server0/listFiles.s

# target to generate assembly for a file
src/server0/listFiles.cpp.s:
	$(MAKE) -f CMakeFiles\server0.dir\build.make CMakeFiles/server0.dir/src/server0/listFiles.cpp.s
.PHONY : src/server0/listFiles.cpp.s

src/server0/server0.obj: src/server0/server0.cpp.obj

.PHONY : src/server0/server0.obj

# target to build an object file
src/server0/server0.cpp.obj:
	$(MAKE) -f CMakeFiles\server0.dir\build.make CMakeFiles/server0.dir/src/server0/server0.cpp.obj
.PHONY : src/server0/server0.cpp.obj

src/server0/server0.i: src/server0/server0.cpp.i

.PHONY : src/server0/server0.i

# target to preprocess a source file
src/server0/server0.cpp.i:
	$(MAKE) -f CMakeFiles\server0.dir\build.make CMakeFiles/server0.dir/src/server0/server0.cpp.i
.PHONY : src/server0/server0.cpp.i

src/server0/server0.s: src/server0/server0.cpp.s

.PHONY : src/server0/server0.s

# target to generate assembly for a file
src/server0/server0.cpp.s:
	$(MAKE) -f CMakeFiles\server0.dir\build.make CMakeFiles/server0.dir/src/server0/server0.cpp.s
.PHONY : src/server0/server0.cpp.s

src/server0/upload.obj: src/server0/upload.cpp.obj

.PHONY : src/server0/upload.obj

# target to build an object file
src/server0/upload.cpp.obj:
	$(MAKE) -f CMakeFiles\server0.dir\build.make CMakeFiles/server0.dir/src/server0/upload.cpp.obj
.PHONY : src/server0/upload.cpp.obj

src/server0/upload.i: src/server0/upload.cpp.i

.PHONY : src/server0/upload.i

# target to preprocess a source file
src/server0/upload.cpp.i:
	$(MAKE) -f CMakeFiles\server0.dir\build.make CMakeFiles/server0.dir/src/server0/upload.cpp.i
.PHONY : src/server0/upload.cpp.i

src/server0/upload.s: src/server0/upload.cpp.s

.PHONY : src/server0/upload.s

# target to generate assembly for a file
src/server0/upload.cpp.s:
	$(MAKE) -f CMakeFiles\server0.dir\build.make CMakeFiles/server0.dir/src/server0/upload.cpp.s
.PHONY : src/server0/upload.cpp.s

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... edit_cache
	@echo ... rebuild_cache
	@echo ... server0
	@echo ... src/common/fileExist.obj
	@echo ... src/common/fileExist.i
	@echo ... src/common/fileExist.s
	@echo ... src/server0/download.obj
	@echo ... src/server0/download.i
	@echo ... src/server0/download.s
	@echo ... src/server0/listFiles.obj
	@echo ... src/server0/listFiles.i
	@echo ... src/server0/listFiles.s
	@echo ... src/server0/server0.obj
	@echo ... src/server0/server0.i
	@echo ... src/server0/server0.s
	@echo ... src/server0/upload.obj
	@echo ... src/server0/upload.i
	@echo ... src/server0/upload.s
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

